### ISSUE TITLE
Changing color of gutter handle

### ISSUE THREAD

**Issue by sergei-dyshel** [artem-barmin/obsidian-block-drag-n-drop#22]
What is the right way to override color of gutter marker?
I tried adding CSS snippet:
```css
.dnd-gutter-marker {
    color: yellow
}
```

but that doesn't work.
