### ISSUE TITLE
FR: Show drag handle only on hover

### ISSUE THREAD

**Issue by imeed166** [artem-barmin/obsidian-block-drag-n-drop#5]
Just like in notion, show drag handle only when hovering over a line.

https://user-images.githubusercontent.com/38974541/163826861-e4570157-b24d-4328-8521-ac6a7e8dcc78.mov

**Comment by artem-barmin** [comment]
Nice idea. But ration "value/cost" is too low. It's quite costly to create this feature, while value is purely visual. You can create css snippet that will show handler only during hovering the gutter itself:

```css
.dnd-gutter-marker {
    opacity: 0;
}

.dnd-gutter-marker:hover {
    opacity: 1;
}
```
